package com.zdxt.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

public class ActivityProgram implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "1011010101")
    private String id;

    @ApiModelProperty(example = "内容消息")
    private String content;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "活动标题")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "2010-03-15 06:11")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.remark
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "备注信息")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.addr
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "成都")
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "2010-03-15 06:11")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "0")
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "0")
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_program.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.id
     *
     * @return the value of activity_program.id
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.id
     *
     * @param id the value for activity_program.id
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.title
     *
     * @return the value of activity_program.title
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.title
     *
     * @param title the value for activity_program.title
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.create_time
     *
     * @return the value of activity_program.create_time
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.create_time
     *
     * @param createTime the value for activity_program.create_time
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.remark
     *
     * @return the value of activity_program.remark
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.remark
     *
     * @param remark the value for activity_program.remark
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.addr
     *
     * @return the value of activity_program.addr
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.addr
     *
     * @param addr the value for activity_program.addr
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.update_time
     *
     * @return the value of activity_program.update_time
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.update_time
     *
     * @param updateTime the value for activity_program.update_time
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.kind
     *
     * @return the value of activity_program.kind
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.kind
     *
     * @param kind the value for activity_program.kind
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.flag
     *
     * @return the value of activity_program.flag
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.flag
     *
     * @param flag the value for activity_program.flag
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_program.content
     *
     * @return the value of activity_program.content
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_program.content
     *
     * @param content the value for activity_program.content
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "ActivityProgram{" +
                "id='" + id + '\'' +
                ", content='。。。" + content + '\'' +
                ", title='" + title + '\'' +
                ", createTime=" + createTime +
                ", remark='" + remark + '\'' +
                ", addr='" + addr + '\'' +
                ", updateTime=" + updateTime +
                ", kind='" + kind + '\'' +
                ", flag=" + flag +
                '}';
    }
}