package com.zdxt.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class CooperativeResources implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.url
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */

    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.description
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.logo
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperative_resources.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.id
     *
     * @return the value of cooperative_resources.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.id
     *
     * @param id the value for cooperative_resources.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.url
     *
     * @return the value of cooperative_resources.url
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.url
     *
     * @param url the value for cooperative_resources.url
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.title
     *
     * @return the value of cooperative_resources.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.title
     *
     * @param title the value for cooperative_resources.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.create_time
     *
     * @return the value of cooperative_resources.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.create_time
     *
     * @param createTime the value for cooperative_resources.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.update_time
     *
     * @return the value of cooperative_resources.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.update_time
     *
     * @param updateTime the value for cooperative_resources.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.description
     *
     * @return the value of cooperative_resources.description
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.description
     *
     * @param description the value for cooperative_resources.description
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.logo
     *
     * @return the value of cooperative_resources.logo
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.logo
     *
     * @param logo the value for cooperative_resources.logo
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.kind
     *
     * @return the value of cooperative_resources.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.kind
     *
     * @param kind the value for cooperative_resources.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperative_resources.flag
     *
     * @return the value of cooperative_resources.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperative_resources.flag
     *
     * @param flag the value for cooperative_resources.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    @Override
    public String toString() {
        return "CooperativeResources{" +
                "id='" + id + '\'' +
                ", url='" + url + '\'' +
                ", title='" + title + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", description='" + description + '\'' +
                ", logo='" + logo + '\'' +
                ", kind='" + kind + '\'' +
                ", flag=" + flag +
                '}';
    }
}