package com.zdxt.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

@ApiModel(value = "德国新闻类",description = "德国新闻类")
public class GermanyNews implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "1011010101")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "新闻标题")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "2010-03-12 12:11")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "2010-03-15 06:11")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.author
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "作者")
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "0")
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germany_news.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @ApiModelProperty(example = "<span class=\"bjh-p\"><span class=\"bjh-strong\">雷锋网 AI 开发者按：</span>11 月 2-3 日，由开源社举办的「开源无疆、携手出航」2019 中国开源年会 ( COSCon'19 ) 于华东师范大学顺利落下帷幕。大会上，来自全国各地的专家、大师齐聚一堂，向广大开发者们分享了与开源相关的各种甜酸苦辣。</span>")
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.id
     *
     * @return the value of germany_news.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.id
     *
     * @param id the value for germany_news.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.title
     *
     * @return the value of germany_news.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.title
     *
     * @param title the value for germany_news.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.create_time
     *
     * @return the value of germany_news.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.create_time
     *
     * @param createTime the value for germany_news.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.update_time
     *
     * @return the value of germany_news.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.update_time
     *
     * @param updateTime the value for germany_news.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.author
     *
     * @return the value of germany_news.author
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.author
     *
     * @param author the value for germany_news.author
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.flag
     *
     * @return the value of germany_news.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.flag
     *
     * @param flag the value for germany_news.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germany_news.content
     *
     * @return the value of germany_news.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germany_news.content
     *
     * @param content the value for germany_news.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "GermanyNews{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", author='" + author + '\'' +
                ", flag=" + flag +
                ", content='" + content + '\'' +
                '}';
    }
}