package com.zdxt.model;

import java.io.Serializable;

public class IndexBanner implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_banner.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_banner.img
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_banner.descrip
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String descrip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_banner.id
     *
     * @return the value of index_banner.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_banner.id
     *
     * @param id the value for index_banner.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_banner.img
     *
     * @return the value of index_banner.img
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_banner.img
     *
     * @param img the value for index_banner.img
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_banner.descrip
     *
     * @return the value of index_banner.descrip
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getDescrip() {
        return descrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_banner.descrip
     *
     * @param descrip the value for index_banner.descrip
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setDescrip(String descrip) {
        this.descrip = descrip == null ? null : descrip.trim();
    }

    @Override
    public String toString() {
        return "IndexBanner{" +
                "id='" + id + '\'' +
                ", img='" + img + '\'' +
                ", descrip='" + descrip + '\'' +
                '}';
    }
}