package com.zdxt.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class IndexNews implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.description
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.first_picture
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String firstPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.level
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.author
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_news.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.id
     *
     * @return the value of index_news.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.id
     *
     * @param id the value for index_news.id
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.title
     *
     * @return the value of index_news.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.title
     *
     * @param title the value for index_news.title
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.create_time
     *
     * @return the value of index_news.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.create_time
     *
     * @param createTime the value for index_news.create_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.update_time
     *
     * @return the value of index_news.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.update_time
     *
     * @param updateTime the value for index_news.update_time
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.description
     *
     * @return the value of index_news.description
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.description
     *
     * @param description the value for index_news.description
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.first_picture
     *
     * @return the value of index_news.first_picture
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getFirstPicture() {
        return firstPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.first_picture
     *
     * @param firstPicture the value for index_news.first_picture
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setFirstPicture(String firstPicture) {
        this.firstPicture = firstPicture == null ? null : firstPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.kind
     *
     * @return the value of index_news.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.kind
     *
     * @param kind the value for index_news.kind
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.flag
     *
     * @return the value of index_news.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.flag
     *
     * @param flag the value for index_news.flag
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.level
     *
     * @return the value of index_news.level
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.level
     *
     * @param level the value for index_news.level
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.author
     *
     * @return the value of index_news.author
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.author
     *
     * @param author the value for index_news.author
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_news.content
     *
     * @return the value of index_news.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_news.content
     *
     * @param content the value for index_news.content
     *
     * @mbggenerated Thu Nov 07 19:52:19 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "IndexNews{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", description='" + description + '\'' +
                ", firstPicture='" + firstPicture + '\'' +
                ", kind='" + kind + '\'' +
                ", flag=" + flag +
                ", level=" + level +
                ", author='" + author + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}