package com.zdxt.model;

import java.io.Serializable;

public class ZdUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_user.id
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_user.username
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_user.password
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_user.name
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_user.email
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zd_user.phone
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_user.id
     *
     * @return the value of zd_user.id
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_user.id
     *
     * @param id the value for zd_user.id
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_user.username
     *
     * @return the value of zd_user.username
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_user.username
     *
     * @param username the value for zd_user.username
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_user.password
     *
     * @return the value of zd_user.password
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_user.password
     *
     * @param password the value for zd_user.password
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_user.name
     *
     * @return the value of zd_user.name
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_user.name
     *
     * @param name the value for zd_user.name
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_user.email
     *
     * @return the value of zd_user.email
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_user.email
     *
     * @param email the value for zd_user.email
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zd_user.phone
     *
     * @return the value of zd_user.phone
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zd_user.phone
     *
     * @param phone the value for zd_user.phone
     *
     * @mbggenerated Fri Nov 08 16:56:31 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    @Override
    public String toString() {
        return "ZdUser{" +
                "id='" + id + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                '}';
    }
}